"""update_achievements_extend_image_length

Revision ID: 067940cf50c4
Revises: 9a3e9bf0a25b
Create Date: 2025-01-23 16:03:41.804725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067940cf50c4'
down_revision = '9a3e9bf0a25b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
