"""added unique constraint to topic scores

Revision ID: 1e528458f318
Revises: abc4ba7573ef
Create Date: 2024-08-05 20:32:15.583121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e528458f318'
down_revision = 'abc4ba7573ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_topic_scores', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_topic_test_score', ['student_id', 'test_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_topic_scores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_topic_test_score', type_='unique')

    # ### end Alembic commands ###
