"""updated the unique constraint

Revision ID: 2521a9da6703
Revises: f5758e36e479
Create Date: 2025-01-21 16:18:54.539049

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2521a9da6703"
down_revision = "f5758e36e479"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("student_topic_scores", schema=None) as batch_op:
        batch_op.drop_constraint("uq_topic_test_score", type_="unique")
        batch_op.create_unique_constraint(
            "uq_topic_test_score", ["student_id", "test_id", "topic_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("student_topic_scores", schema=None) as batch_op:
        batch_op.drop_constraint("uq_topic_test_score", type_="unique")
        batch_op.create_unique_constraint(
            "uq_topic_test_score", ["student_id", "test_id"]
        )

    # ### end Alembic commands ###
