"""streaks

Revision ID: 316376e6c69f
Revises: 37ef6c0da770
Create Date: 2024-08-02 20:38:26.102085

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "316376e6c69f"
down_revision = "37ef6c0da770"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("student", schema=None) as batch_op:
        batch_op.add_column(sa.Column("current_streak", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("highest_streak", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("last_login", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("student", schema=None) as batch_op:
        batch_op.drop_column("last_login")
        batch_op.drop_column("highest_streak")
        batch_op.drop_column("current_streak")

    # ### end Alembic commands ###
