"""update_addIsPremiumToSubject

Revision ID: 322af3c44995
Revises: 5bf70e605741
Create Date: 2025-07-05 20:34:43.645086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322af3c44995'
down_revision = '5bf70e605741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
