"""empty message

Revision ID: 35576ec61a55
Revises: 766cc715c7f2
Create Date: 2024-05-04 08:17:05.503781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35576ec61a55'
down_revision = '766cc715c7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(length=11), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('is_package_school', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    # ### end Alembic commands ###
