"""changed proficiency to string

Revision ID: 37ef6c0da770
Revises: e36e9e87b5bd
Create Date: 2024-08-02 19:05:45.587322

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37ef6c0da770"
down_revision = "e36e9e87b5bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("student_best_subject", schema=None) as batch_op:
        batch_op.alter_column(
            "proficiency_level",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=50),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("student_best_subject", schema=None) as batch_op:
        batch_op.alter_column(
            "proficiency_level",
            existing_type=sa.String(length=50),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
