"""update_isInstructional

Revision ID: 3aaa85b8b90d
Revises: 3b473e6a5b6f
Create Date: 2025-02-11 17:24:01.470444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '3aaa85b8b90d'
down_revision = '3b473e6a5b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_instructional', sa.Boolean(), nullable=True))
        batch_op.alter_column('correct_answer',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('possible_answers',
               existing_type=sa.TEXT(),
               nullable=True)
        
       # Create a temporary table representation for the update
    question_table = table('question',
        column('is_instructional', sa.Boolean)
    )
    
    # Update all existing rows to set is_read to False
    op.execute(
        question_table.update().values(is_instructional=False)
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('possible_answers',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('correct_answer',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('is_instructional')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
