"""update_notificationsToAddIsRead

Revision ID: 3b473e6a5b6f
Revises: 9622e7a72d92
Create Date: 2025-02-11 08:16:05.066516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '3b473e6a5b6f'
down_revision = '9622e7a72d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # Create a temporary table representation for the update
    notification_table = table('notification',
        column('is_read', sa.Boolean)
    )
    
    # Update all existing rows to set is_read to False
    op.execute(
        notification_table.update().values(is_read=False)
    )

    # Make the column non-nullable after setting the default value
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('is_read',
                            existing_type=sa.Boolean(),
                            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###