"""flag_questions

Revision ID: 3d5f3947558a
Revises: c3fba3047c77
Create Date: 2025-01-15 07:03:00.477091

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d5f3947558a"
down_revision = "c3fba3047c77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_flagged", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("flag_reason", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.drop_column("flag_reason")
        batch_op.drop_column("is_flagged")

    # ### end Alembic commands ###
