"""update_addedMaxDurationToSubject

Revision ID: 407ed24ff53c
Revises: 2521a9da6703
Create Date: 2025-01-21 17:14:53.628354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407ed24ff53c'
down_revision = '2521a9da6703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_column('max_duration')

    # ### end Alembic commands ###
