"""empty message

Revision ID: 5bf70e605741
Revises: 24bf26e7a271
Create Date: 2025-06-28 23:04:04.893734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf70e605741'
down_revision = '24bf26e7a271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
