"""create_weeklyGoalsPrep

Revision ID: 72c1ce76243a
Revises: 1a1eb85b8313
Create Date: 2025-10-27 13:37:09.600914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72c1ce76243a'
down_revision = '1a1eb85b8313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_goal',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=True),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'in_progress', 'achieved', 'expired', name='goal_status'), server_default='pending', nullable=False),
    sa.Column('target_metric', postgresql.ENUM('xp', 'streak_days', name='goal_metric'), nullable=False),
    sa.Column('target_value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('current_value >= 0', name='ck_current_value_nonneg'),
    sa.CheckConstraint('target_value >= 0', name='ck_target_value_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'week_start_date', 'target_metric', name='uniq_weekly_goal')
    )
    with op.batch_alter_table('weekly_goal', schema=None) as batch_op:
        batch_op.create_index('idx_weekly_goals_status', ['status'], unique=False)
        batch_op.create_index('idx_weekly_goals_student_week', ['student_id', 'week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_goal_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_goal_student_id'))
        batch_op.drop_index('idx_weekly_goals_student_week')
        batch_op.drop_index('idx_weekly_goals_status')

    op.drop_table('weekly_goal')
    # ### end Alembic commands ###
