"""Add StudentQuestion model for ChatGPT integration

Revision ID: 73e7f6d53bb4
Revises: 3aaa85b8b90d
Create Date: 2025-04-24 11:10:21.299723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e7f6d53bb4'
down_revision = '3aaa85b8b90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
