"""update_addAchievementClassToAchievement

Revision ID: 746aee89b995
Revises: 067940cf50c4
Create Date: 2025-01-23 16:46:10.267232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746aee89b995'
down_revision = '067940cf50c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_class', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_column('achievement_class')

    # ### end Alembic commands ###
