"""payment_status

Revision ID: 78d4fb012ef6
Revises: 86af0ee9c8c4
Create Date: 2024-10-29 11:24:15.915140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d4fb012ef6'
down_revision = '86af0ee9c8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_billing_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=100), server_default='pending', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_billing_history', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
