"""changes to question and minor changes

Revision ID: 838ba5b56804
Revises: ceb9b4b45485
Create Date: 2024-06-23 12:57:23.889895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838ba5b56804'
down_revision = 'ceb9b4b45485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'subject', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subject_id')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
