"""subscriptions

Revision ID: 86af0ee9c8c4
Revises: fdc84ef3520f
Create Date: 2024-10-29 08:46:36.840595

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "86af0ee9c8c4"
down_revision = "fdc84ef3520f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "school_billing_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.Column("amount_due", sa.Float(), nullable=False),
        sa.Column("date_due", sa.Date(), nullable=False),
        sa.Column("billed_on", sa.Date(), nullable=False),
        sa.Column("settled_on", sa.Date(), nullable=True),
        sa.Column("payment_reference", sa.String(length=200), nullable=True),
        sa.Column("subscription_package", sa.String(length=100), nullable=False),
        sa.Column("subscription_start_date", sa.Date(), nullable=False),
        sa.Column("subscription_end_date", sa.Date(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["school.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("school", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "subscription_package",
                sa.String(),
                nullable=True,
                server_default="free",
                default="free",
            )
        )
        batch_op.add_column(
            sa.Column("subscription_expiry_date", sa.Date(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("school", schema=None) as batch_op:
        batch_op.drop_column("subscription_expiry_date")
        batch_op.drop_column("subscription_package")

    op.drop_table("school_billing_history")
    # ### end Alembic commands ###
