"""update_addYearToQuestions

Revision ID: 9622e7a72d92
Revises: a44de0832ec2
Create Date: 2025-02-04 23:54:18.124316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9622e7a72d92'
down_revision = 'a44de0832ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    with op.batch_alter_table('sub_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_flagged', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('flag_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_question', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('flag_reason')
        batch_op.drop_column('is_flagged')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
