"""update_addIsActiveToGoals

Revision ID: 988a3e97c70c
Revises: 72c1ce76243a
Create Date: 2025-11-28 19:54:44.812838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988a3e97c70c'
down_revision = '72c1ce76243a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), default=True, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_goal', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
