"""update_studentHasAchievement

Revision ID: 98b900b10c10
Revises: df920a04db65
Create Date: 2026-01-30 12:15:20.781559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b900b10c10'
down_revision = 'df920a04db65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
