"""update_addAchievementClassToAchievement

Revision ID: a44de0832ec2
Revises: 746aee89b995
Create Date: 2025-01-23 16:47:28.551453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44de0832ec2'
down_revision = '746aee89b995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
