"""add_achievements

Revision ID: d5b91c2b3115
Revises: 407ed24ff53c
Create Date: 2025-01-23 15:44:16.673024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b91c2b3115'
down_revision = '407ed24ff53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
