"""fix for failing migrations

Revision ID: f5758e36e479
Revises: 3d5f3947558a
Create Date: 2025-01-15 07:22:48.058097

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5758e36e479"
down_revision = "3d5f3947558a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.alter_column("is_flagged", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.alter_column("is_flagged", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###
